version: '3.8'
services:
  frontend:
    build: ./loganheatingvue
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build: ./loganheatingJAVA
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logan_heating
      SPRING_DATASOURCE_USERNAME: logan_app_user
      SPRING_DATASOURCE_PASSWORD: logan_app_user
    networks:
      - app-network
  db:
    image: postgres
    environment:
      POSTGRES_DB: logan_heating
      POSTGRES_USER: logan_app_user
      POSTGRES_PASSWORD: logan_app_user
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge







